### ISSUE TITLE
WebSocketClient::send hangs while writing 4 NOOP bytes

### ISSUE THREAD

**Issue by berkley** [ekbduffy/spark_websockets#6]
I'm seeing random hangs on the client during websocket communication between the core and node.js after sending 10-200 messages.  I've tracked this down to the code that writes the NOOP bytes before printing the payload message to the client.  I've done a tcpdump on this and it appears that for some reason the TCP send/ack sequence gets out of order, which causes the client to hang without disconnecting the socket first.  Have you seen this issue before?  Do you know of a workaround?  I can provide you with the tcpdump output if you'd like.  

Another tangentially related question: The version of Spark-Websockets published via the Spark web IDE is different from master in your git repository.  Should I be using the published version or the master version in git?  For what it's worth, I've tried both and had the same result.  

Thanks for any help.

**Comment by ekbduffy** [comment]
Hello, i've not touched this repo for a long time and can't remember why version differs, maybe it's happened during discussions with chuank community.spark.io/t/websockets-client/3090/36 so it's better to use this repo version. Because i didn't use Web IDE, so here can be never version.


What speed of your 10-200 messages? What delay between them? I've stopped to develop this library for now, because of spark sad working with great array of arriving data. It's can't figure out where message ends and begins new. It's just can iterate over tcpbuffer, which filling by CC3000 and dma of stm32 mcu, as i think. So it's possible, that you have very little time between messages and this hangs Core.

**Comment by berkley** [comment]
I've tried varying the delay between messages significantly (50-5000ms) and it always eventually hangs.  I think you're right about the Spark TCP/CC3000 stack being broken.  I've tried similar tests using TCPClient and it will eventually hang or run the core out of memory.  Hopefully they fix it in the photon.  Did you ever get this working with spacebrew?

**Comment by ekbduffy** [comment]
Sure, i've runed my test thru Spacebrew and js client for it on html page :) 
Fastest hang of Spark goes with slider transfering range to Core :)

**Comment by berkley** [comment]
Ha, I could see that.  Anyway, thanks for the help.  I was hopeful I could get this to work for a lighting project I'm doing, but it doesn't seem like the core is performant enough at this point.  I'm pinning my hopes on the Photon if they ever ship it :)

**Comment by ekbduffy** [comment]
I've also planned to use this with lighting projects. Try to look at MQTT transfers for commands. It can be better suitable for MCU's.

**Comment by berkley** [comment]
Great.  Thanks for the tip.
